### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by 1ozturkbe**
@bqpd can you make sure the server works with this model, and merge? I still fundamentally don't understand how we get everything to mesh together. Can you please add to the docs a part about that?

### CODE REVIEW

**Comment by bqpd** [comment]
@1ozturkbe, there's a creation of the heatexchanger model earlier in the server file that has to be made to match the new style. I can do it, but it involves making designHX return an unsolved model, so if you want that done a particular way let me know.

**Comment by 1ozturkbe** [comment]
Oh that's fine, I can do that and push. But why does it need an unsolved instance of the model?

**Comment by bqpd** [comment]
okay great!

**Comment by 1ozturkbe** [comment]
Wait how can you create a new instance of (i.e. copy) the model without rebuilding it? Also, why does it need to be an unsolved instance of the model? Would you mind just making the changes on this branch?

**Comment by bqpd** [comment]
will do!

**Comment by bqpd** [comment]
@1ozturkbe if you approve my changes in the commit above, this is ready to merge!

**Comment by 1ozturkbe** [comment]
Looks good, merging!

**Pull request merged**
