### PR TITLE
Berk's latest model with the interactive changes

### PR DESCRIPTION
**Pull request by bqpd**
and some lint by Ned

@1ozturkbe, particularly check if the last `lint` commit makes sense; it doesn't change the results at all.

### CODE REVIEW

**Comment by bqpd** [comment]
@1ozturkbe could you take a look at the list of design parameters that will be controlled from within ESP in `layer.py`? I'm wondering if number of fins or something similar should be added to it...

**Comment by 1ozturkbe** [comment]
It should be at some point, since n_fins is now a variable in layer. I wanted to allow non-integer number of fins in case a user had no idea what that number should be.

**Comment by bqpd** [comment]
Great! Does the syntax for the specification of design parameters look good to you?

**Comment by 1ozturkbe** [comment]
Can we not call them air and water channels? I don't know why we started with those in the first place. They should just be called hot and cold channels.

**Comment by 1ozturkbe** [comment]
I have totally removed mentions of air and water in berkMaster. It's just confusing.

**Comment by bqpd** [comment]
Sounds like a good plan!

**Comment by 1ozturkbe** [comment]
O/w everything looks good.

**Comment by bqpd** [comment]
What about for material properties, should we use cold/hot instead of air/water there as well?

**Comment by 1ozturkbe** [comment]
Definitely, should be agnostic to the fluid.

**Pull request merged**
